SET ECHO ON;
SET LINESIZE 120;
SET PAGESIZE 60;

CREATE SEQUENCE seq_patient_id START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE seq_hospital_id START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE seq_record_id START WITH 5000 INCREMENT BY 1;
CREATE SEQUENCE seq_match_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_alert_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_log_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_normalized_id START WITH 1 INCREMENT BY 1;

COMMIT;